### ISSUE TITLE
Strong eventual consistency? 

### ISSUE THREAD

**Issue by silasdavis** [zerotier/lf#9]
Is LF (possibly in combination with conflict resolution mechanisms) able to provide monotic eventual consistency? In particular:

- nodes receiving same updates in any order will have same values for all keys
- a read from the same node will not return an older value for a key after receiving additional updates having previously returned a newer value (no rollback)

**Comment by adamierymenko** [comment]
The answer to both of these is that it depends on which conflict resolution mechanism is selected in the query.

The default is a metric called `trust` that is computed from a mixture of proof of work, certificate signatures (if any) as signals of legitimacy, local node record receive order, and the commentary of any nodes indicated as trust oracles in the query.

Here's an example of how trust oracles might be used:

Let's say Pied Piper, Inc. decides to become a customer of ZeroTier, Inc. and wants to run their own root servers. To do this they run their own LF instance(s) in their private cloud. Since they trust ZeroTier they configure their root servers to specify ZeroTier's LF instances as trust oracles whose opinion will be counted alongside their own local node's heuristics in resolving any conflicts. So let's say ZeroTier's nodes see a later record attempting to usurp the keys of an earlier record. They generate commentary that says "usurping record looks suspicious" and publish it. Pied Piper's queries then see this commentary and the trust of those new usurping records gets adjusted down. 

The oracle/commentary mechanism is analogous to key signing webs of trust but far less manual and clunky. All you need to know to trust an oracle is the record owner under which that oracle is publishing its commentary. It's of course up to you to choose which oracles you feel like trusting. Commentary that isn't trusted is ignored so there is no commentary spam by Sybils has no effect... unless the Sybil can trick you into thinking it's trustworthy and electing to trust it. But that's something that's almost universally true for any and all networked systems. Even a "hard" block chain like Bitcoin can be attacked in this manner if someone can e.g. intercept your `git pull` of the Bitcoin source code and change the genesis information and then trick you into thinking their chain is the global one.

The code for all this is in `api-query.go` which is where the guts of the query algorithm are located. Lower level guts are also in `native/db.c` but that code just queries the index (in SQLite) and generates a raw list of candidate records matching the queried selectors.

As I said, `trust` is the default metric. If you instead choose `weight` then proof of work alone is used to disambiguate. In this case an attacker with a ton of compute power could run the PoW function a whole lot and create a heavier record.

Another option is `timestamp`. This is for cases where you want records in temporal order and don't care about trust. This could be used to implement something like a pub-sub bus where lots of people store records to the same key and clients listen for them.

A core part of the design philosophy of this system is the capacity to offer multiple ways to resolve conflicts and to be open to iteratively improvement of these mechanisms. The DAG is the same everywhere but the way "views" of the DAG are constructed is something that can be improved over time.

Other security mechanisms can be employed by app authors too. For example if you're storing anything identified by a public key you can self-sign the record. After querying the client can iterate through the list of results in order of LF's trust metric and then check the self-signature, tossing any records that aren't properly signed even if they appear higher up in the ranking. Obviously not all use cases can leverage that technique, but it's just one example of clever things that can be done in schema design or at the app level to add defense in depth.

**Comment by adamierymenko** [comment]
One more comment:

There's no silver bullet here. Bitcoin's PoW mechanism is not really a silver bullet as it's fabulously expensive. It consumes as much electricity as a medium sized nation to secure a rather small database. Our approach is not a silver bullet either. We take a multi-paradigm approach where we use some (but much less) proof of work combined with heuristics designed to allow human relationships to be leveraged. We think this will be cheaper and perhaps also more decentralized than runaway PoW, as runaway PoW tends to get very centralized due to industrial economies of scale.
